### ISSUE TITLE
respond_to does not understand HTTP accept formats

### ISSUE THREAD

**Issue by fgrehm** [caelum/restfulie#19]
The problem appeared after updating from 0.4 to 0.6 when requesting a resource from a xml representation.
- Server response code: **406 - Not Acceptable**
- Client request accept header: **application/xml**
- [Controller's code](http://github.com/caelum/restfulie-test/blob/a7e477894e1d2aafd0d5689cd50faa0740c52331/app/controllers/orders_controller.rb)

Firing up console and running "Restfulie.at('http://localhost:3000/orders/1').get" gives me back an Hashi::CustomHash object with resource's html representation. A solution proposed by Guilherme that fixed the problem for show action was to use **render_resource** instead of **respond_to**. I haven't updated the rest of controller's code to use **render_created** and **render_collection** to find out what happens.

Don't know if it helps but trying to fix the bug I've found out that commenting lines below [this one](http://github.com/caelum/restfulie/blob/master/lib/restfulie/media_type_defaults.rb#L43) makes respond_to work properly again.

**Comment by pahagon** [comment]
This code does not exist any more.
