### ISSUE TITLE
Implement POST, PUT request parameters parsing driven by media types

### ISSUE THREAD

**Issue by lfcipriani** [caelum/restfulie#35]
Rails already offer a way to set a media type parameter parsing scheme, as the documentation shows:

```
 # Assign a new param parser to a new content type
ActionController::Base.param_parsers['application/atom+xml'] = Proc.new do |data| 
    node = REXML::Document.new(post) 
   { node.root.name => node.root }
end
```

Therefore, Restfulie must implement a way to enable the user to set specific media types and also support the common ones.

Rails already support XML, JSON and YAML. This feature should also include atom+xml.

**Comment by guilhermesilveira** [comment]
moved to lighthouse
