### ISSUE TITLE
remove restbuy test interaction

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/restfulie#46]
the restfulie restbuy project requires human interaction on localhost:3000/admin
instead of waiting it shoul do a straight request tothe admin interface to settle the payment and then check again!

**Comment by abstractj** [comment]
Got it :D

**Comment by abstractj** [comment]
Let me know if I understood the problem, when I call http://localhost:3000/

This show me a list of products, if I add some product I'll be redirected to orders page, like http://localhost:3000/orders/3

You need be redirected in to admin page when you call http://localhost:3000/ or when you click in create payment button?

**Comment by guilhermesilveira** [comment]
Hi Bruno,

Its a little bit different.
Take a look at client_spec.rb
To run it:

rails server &
rake spec

It will hang. If you see the code, the last test will wait for you to approve a payment. It will post the order, post the payment and wait for approval. Right now, this approval needs to be done by hand, by going to admin, selecting the payment, clicking on it, and choosing "paid". Then the test finishes green.

This last step (waiting and doing the manual click) should simulate the human behavior of clicking and changing to paid (although not following any link!).

Thats it. Let me know if its still unclear... i can probably share my screen

**Comment by abstractj** [comment]
I think that is possible to close now

**Comment by guilhermesilveira** [comment]
great job!
