### ISSUE TITLE
Link restfuliesite/issuetracking to a wiki page

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/restfulie#50]
Link it to a wiki page that mentions and links to all github projects and their issues

**Comment by abstractj** [comment]
Got it :D

**Comment by abstractj** [comment]
according with these changes we could close this issue

https://github.com/caelum/restfulie/wiki
https://github.com/caelum/restfulie/pull/56

**Comment by abstractj** [comment]
I think that this issue can be closed
