### ISSUE TITLE
transform it into a gem

### ISSUE THREAD

**Issue by caelum** [caelum/restfulie#6]
transforming it into a gem will make our development / test process easier

we should use jeweler / gemcutter

**Comment by dcrec1** [comment]
As today, to install restfulie as a gem you can execute:

rake install

To push it to gemcutter:

rake push pkg/restfulie-x.y.z.gem

**Comment by caelum** [comment]
So we need to configure it to show 'caelum' as part of the gem name

**Comment by dcrec1** [comment]
Im Gemcutter the gem names are being set without the author nick, like in Rubyforge.

There are some people that are naming the gems like author-gem_name, like Hashrocket:

http://gemcutter.org/gems/hashrocket-gherkinspec

but IMHO this is kind of ugly.

Rubygems specification has already a place to name the author of the gem and this is read by Gemcutter and displayed in the gem page.

Anyway, you need to create an account for Caelum in Gemcutter and then push the gem with this credentials.

If you need to change the specification of the gem, it can be done in the Rakefile file.
