### ISSUE TITLE
tokamak Rails3 compliance warning

### ISSUE THREAD

**Issue by fredv** [caelum/restfulie#61]
hi there,

thanks for your great set of useful hypermedia gems. we will release a geodatabase service and wrapper gem soon, utilizing restfulie.

since we are developing in 1.9.2 and rails3 we encountered the warning:

DEPRECATION WARNING: exempt_from_layout is no longer needed, because layouts in Rails 3 are restricted to the content-type of the template that was rendered. 

/lib/tokamak/hook/rails.rb:73

In Rails3 it works fine just without the line so there could simply be added a condition to exclude this in a rails 3 gem stack.

keep up the great work!

kind regards,
Frederik

**Comment by guilhermesilveira** [comment]
Hi Frederik! Great. Ill patching it this today and will get back to you.
Is it a public hypermedia API that you are going to release?

Regards

**Comment by guilhermesilveira** [comment]
Hi Frederik,

It seems like rails3 is not working as mentioned. Are we doing something wrong?
I've removed the line and inserted a template on the integration test and its failing. Can you check it here at this branch ("layout" branch)?
https://github.com/caelum/tokamak/tree/layout

If there is a layout for html and we require a json, rails is using the template

Regards

**Comment by guilhermesilveira** [comment]
Sorry, I was testing with Rails 2. My fault. Fixed on the same branch. 
Can you confirm it solves the warning in your case too by building the gem from the branch I've mentioned?

Regards

**Comment by fredv** [comment]
hi guilherme,

my gem / service is not finished - as we are trying to integrate some other data sources first - but can be accessed in its early stages through http://opengeo.dynport.de .

Your branch patch worked for the warning above, but as we are using the 'object_id_compatible' branch (1.9.x), we would love to see it merged into that branch as well.

thanks for the fast response!

**Comment by guilhermesilveira** [comment]
Hi Frederik,

Done. I've merged both into 'object_id_compatible'.
Nice, I've played around with the site's interface. Do you have any idea when its going to be officialy released? We would be gled to help announcing it

Regards

**Comment by fredv** [comment]
Thanks, the branch is warning-free now :D. 

We are integrating the service in one of our startups and will try it out a little in this context first. The service itself will be released in March and I would be thankful for any announcement then!

**Comment by guilhermesilveira** [comment]
Great. I will be working to pull those changes into trunk or otherwise just patch it into Restfulie. Let me know when you have the API ready and I willl make sure to post some news about it too.
