### ISSUE TITLE
rake build and rake install are not working

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/restfulie#62]
rake build should build the gem
rake install should locally install it

**Comment by abstractj** [comment]
gem build restfulie.gemspec does not solve the problem?

**Comment by guilhermesilveira** [comment]
yep :) gem build restfulie.gemspec > pkg && gem install -l pkg/x.gem
its just a shortcut for those two lines when you want to test them

for deployment, runing those two lines once is fine

**Comment by abstractj** [comment]
Take a look at pull request :D

**Comment by guilhermesilveira** [comment]
well done! thanks. wanna go for a deeper one? there are 3 new ones!

**Comment by abstractj** [comment]
Course! I'm just finishing some tasks to conquest the world and will restify myself :D

**Comment by guilhermesilveira** [comment]
Just let me know which one!

On 13/03/2011 7:35 PM, "abstractj" <
reply@reply.github.com>
wrote:

Course! I'm just finishing some tasks to conquest the world and will restify
myself :D

https://github.com/caelum/restfulie/issues/62#comment_867114

**Comment by abstractj** [comment]
I will work next days with issues: 47, 51

**Comment by guilhermesilveira** [comment]
66 is also cute if you want

**Comment by abstractj** [comment]
Don't worry, I've pick up this ticket too. Clojure devs don't love me
