### ISSUE TITLE
Installing Restfulie on 1.6.2 means installing sqlite3

### ISSUE THREAD

**Issue by jeroenvandijk** [caelum/restfulie#77]
The gemspec has `add_dependency 'sqlite3-ruby'` when the rubygems version is greater or equal to 1.2.0. I think this should be reversed because when I install restfulie with rubygems 1.6.2 on ruby 1.9.2-p180 it also pulls in sqlite3

I'm talking about this line: https://github.com/caelum/restfulie/blob/master/restfulie.gemspec#L34

I tried to experiment with rubygems 1.2.0 to see how that worked, but i didn't get that working according to these [instructions](http://beginrescueend.com/rubies/rubygems/)

Can someone check with rubygems 1.2.0 and see how that works? I would prefer not to include sqlite3 as a dependency for my application

Thanks a lot!

**Comment by guilhermesilveira** [comment]
Hello,

Is not it weird?
For >= 1.2.0 (in your case 1.6.2) it should only download sqlite3 if
its downloading dev dependencies, correct?
The default behavior of rubygems would be to not include dev
dependencies, as there is --development to include them. Maybe its
another gem required by restfulie that adds it?

I am using 1.8.2 and I get the same problem, it downloads dev gems by
default. How can we config not to do it by default but only for the
dev environment?

Regards

Guilherme Silveira
Caelum | Ensino e Inovação
http://www.caelum.com.br/

On Thu, Jul 28, 2011 at 8:36 AM, jeroenvandijk
reply@reply.github.com
wrote:

**Comment by jeroenvandijk** [comment]
Hmm you are right. It seems to be a rubygems issue.

My Gemfile.lock tells me that it is restfulie pulling in the sqlite3 dependency:

```
restfulie (1.0.3)
  hypertemplate (~> 1.2.0)
  json_pure (>= 1.2.4)
  medie (~> 1.0.0)
  nokogiri (>= 1.4.2)
  rack-conneg
  respondie (~> 0.9.0)
  sqlite3-ruby
```

I have a fix here: https://github.com/caelum/restfulie/pull/78
